import type { DocumentKey, LegalTransactionType } from "@/lib/types/legal";
import { DOCUMENT_KEY_LABELS } from "@/lib/types/legal";

// Template Registry: a static catalog of document *shapes*, not legal content. Every body is a
// generic, non-jurisdiction-specific worksheet that lists the facts an attorney will need --
// it is never phrased as usable contract language, and it never cites or paraphrases any
// statute. This is deliberate: "document assembly" here means turning deal facts into an
// attorney intake packet per document type, not generating something a non-lawyer could mistake
// for a signable contract.
//
// distressed_property_documents is intentionally excluded -- a case that reaches that fact
// pattern needs attorney-drafted documents from scratch, never a generic template.

export const NEVER_TEMPLATED_KEYS: DocumentKey[] = ["distressed_property_documents"];

export interface TemplateRegistryEntry {
  key: DocumentKey;
  name: string;
  transactionType: LegalTransactionType | null;
  description: string;
}

export const TEMPLATE_REGISTRY: TemplateRegistryEntry[] = (
  [
    "purchase_agreement",
    "existing_financing_addendum",
    "subject_to_disclosure",
    "seller_acknowledgment",
    "due_on_sale_disclosure",
    "servicing_agreement",
    "payment_authorization",
    "insurance_requirements",
    "attorney_review_provision",
    "title_closing_instructions",
    "property_condition_disclosure",
    "jurisdiction_specific",
    "seller_finance_note",
    "seller_finance_security_instrument",
    "hybrid_seller_carry_addendum",
    "other_attorney_addenda",
  ] as DocumentKey[]
).map((key) => ({
  key,
  name: DOCUMENT_KEY_LABELS[key],
  transactionType: null,
  description: `Attorney intake worksheet for: ${DOCUMENT_KEY_LABELS[key]}.`,
}));

export function buildPlaceholderBody(name: string): string {
  return [
    "=============================================================",
    "PLACEHOLDER -- NOT A CONTRACT -- DO NOT SIGN OR PRESENT TO A SELLER",
    `Document type: ${name}`,
    "=============================================================",
    "",
    "This is a structural worksheet generated by Property Deal Analyzer. It contains no",
    "attorney-drafted legal language, cites no statute, and creates no rights or obligations.",
    "It exists only to hand an attorney the deal facts already captured in this app so they can",
    "draft the real document. It must never be shown to a seller, signed by anyone, or relied on",
    "as a functioning agreement.",
    "",
    "CAPTURED FACTS (for the attorney's reference only):",
    "{{FIELDS_BLOCK}}",
    "",
    "=============================================================",
    "Attorney review status: {{ATTORNEY_REVIEW_STATUS}}",
    "Until an attorney licensed in the property's jurisdiction replaces this worksheet with",
    "drafted language and the parties properly execute that document, nothing here is",
    "enforceable and nothing here should be treated as legal advice.",
    "=============================================================",
  ].join("\n");
}
